### ISSUE TITLE
"File not found" in place of the content in Dash

### ISSUE THREAD

**Issue by ilyabo** [dlokesh/clojuredocs-docset#1]
The compiled docset does not work in Dash for me :( The entries show up in the list and the search works, but the content of the entries is not shown. What can be the reason?

![screen shot 2013-11-20 at 11 37 41](https://f.cloud.github.com/assets/351828/1590469/177e4e18-5290-11e3-9bc3-01d610a30c71.png)

**Comment by dlokesh** [comment]
Looks like a path issue. 

From the command line, can you go inside clojure-docs.docset and do a `find .` and post the output here. Also if you could share the index file `clojure-docs.docset/Contents/Resources/docSet.dsidx`, it would be helpful to find the issue.

**Comment by ilyabo** [comment]
Sure! Here you go:
https://dl.dropboxusercontent.com/u/872077/clojuredocs-dash/contents.txt
https://dl.dropboxusercontent.com/u/872077/clojuredocs-dash/docSet.dsidx

**Comment by dlokesh** [comment]
There is a defect in populating the sqlite db. For eg:

```
sqlite> select * from searchIndex where name = 'when-not';
829|when-not|Function|clojure_core/clojure.core/when-not.html
```

It should actually be:

```
829|when-not|Function|clojuredocs.org/clojure_core/clojure.core/when-not.html
```

I'll start working on the fix. In the meanwhile you can manually update the index to get going:

```
cd clojure-docs.docset/Contents/Resources/Documents
sqlite3 docSet.dsidx
sqlite> update searchIndex set path = 'clojuredocs.org/'||path;
```

After that just re-import the docset. Thank you for reporting.

**Comment by ilyabo** [comment]
Did I miss something?

```
clojure-docs $ cd clojure-docs.docset/Contents/Resources/Documents
Documents $ sqlite3 docSet.dsidx
SQLite version 3.7.13 2012-07-17 17:46:21
Enter ".help" for instructions
Enter SQL statements terminated with a ";"
sqlite> update searchIndex set path = 'clojuredocs.org/'||path;
Error: no such table: searchIndex
```

**Comment by dlokesh** [comment]
Thats strange, I used the same docSet.dsidx file that you shared in dropbox and I was able to do the update. Could you confirm you are using the right docSet.dsidx ?

**Comment by ilyabo** [comment]
It works now, thanks! My docSet.dsidx was corrupt for some reason. Just one correction: it is in clojure-docs.docset/Contents/Resources, not in .../Documents

**Comment by dlokesh** [comment]
Oh, thats my bad. Sorry.

Defect has been fixed. Closing this issue.
